name: Publish Docker Image

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Build and pack home-assistant-matter-hub
        run: |
          cd apps/home-assistant-matter-hub
          pnpm install --frozen-lockfile
          pnpm build
          pnpm run pack

      - name: Install dependencies and pack docker standalone
        run: |
          cd apps/docker/standalone
          pnpm install --frozen-lockfile
          pnpm pack --out package.tgz
          mv ../package.tgz .

      - name: Build and push Docker image (sha and latest tags)
        run: |
          cd apps/docker
          pnpm exec node retrieve-package.js
          cd standalone
          ./build.sh --sha ${{ steps.vars.outputs.sha_short }} --push --latest --all-platforms
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled